'use client';

import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { Provider } from 'react-redux';
import { store } from '@/redux/store.js';
import Header from '@/components/Header';
import { useAuthCheck } from '@/hooks/useAuth';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

function RootLayoutContent({ children }) {
  useAuthCheck();

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased m-auto w-4/4`}>
        <Header />
        {children}
        <Toaster />
      </body>
    </html>
  );
}

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <RootLayoutContent>{children}</RootLayoutContent>
    </Provider>
  );
}
